# beginning of app.yaml  
runtime: nodejs16
env: standard 
runtime_config:   
  nodejs_version: 16

#entrypoint: npm start

handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html



