# beginning of app.yaml  
runtime: python
service: backend
env: flex 
runtime_config:   
  python_version: 3.7

entrypoint: gunicorn -b :$PORT api:app 

env_variables:     
  DB_STRING: >- 
    postgresql+psycopg2://postgres:JpL|D?3~zVQ{E6.R@/db?host=/cloudsql/cs331e-idb-377815:us-central1:allaboutsoccer 
beta_settings:
  cloud_sql_instances: cs331e-idb-377815:us-central1:allaboutsoccer
manual_scaling:   
  instances: 1 
resources:   
  cpu: 1   
  memory_gb: 0.5   
  disk_size_gb: 10  
# end of app.yaml